### ISSUE TITLE
Redesigning the model to account for receipt storage features

### ISSUE THREAD

**Issue by BREG001** [UmWooNeAh/GroupSettlement2#30]
영수증 저장 기능을 고려한 모델 재설계
@anaconda77 이 @gunwoo99 에게 Riverpod API 사용방법 인수인계 받아서 API 사용을 고려한 설계 필요

**Comment by BREG001** [comment]
마이페이지의 알람 미리보기 부분도 고려 필요

**Comment by anaconda77** [comment]
1) 뷰모델 테스트를 통한 뷰모델/모델 코드 수정
2) 영수증 보관함을 구현하기 위해 유저뷰모델에 myReceipts 객체 추가
3) 정산 합치기 구현하기 위해 그룹뷰모델에 mergeGroup 객체와 merge/remerge 메소드 추가
